Monitoring 2
gis23/microservices pull request #5
Opened 2017-12-24 20:03 UTC by gis23

Добавили cadvisor для сбора метрик с контейнеров. 
Прикрутили grafana для информативных и красивых дашбордов.
Настроили alertmanager для prometheus чтобы слал алерты в slack чат

2017-12-27 13:45 UTC, chromko requested changes
Нужно исправить несколько моментов.

2017-12-27 13:45 UTC, chromko commented on docker-compose.yml
> +      - '9090:${prometheus_port}'
Думаю переменные портов и нужно местами поменять. Иначе параметризуется внутренний порт контейнера, а не тот, который забинден на хосте.

2017-12-27 13:45 UTC, chromko commented on docker-compose.yml
> +      - 3000:${grafana_port}
Та же история с портами

2017-12-27 13:45 UTC, chromko commented on docker-compose.yml
> +      - 9093:${alertmanager_port}
То же самое про порты

2017-12-27 13:45 UTC, chromko commented on README.md
> +edit `alertmanager/config.yml` file with your webhook uri and chanelname
тут про config.yml.example написать бы

2017-12-27 13:45 UTC, chromko commented on comment/build_info.txt
> +713dce6
файлы build_info.txt лучше не комитить и добавить в .gitignore

2017-12-27 13:45 UTC, chromko commented on docker-compose.yml
> +      - '8080:${cadvisor_port}'
Та же проблема с портами

2017-12-27 18:05 UTC, gis23 commented on comment/build_info.txt
> +713dce6
Вроде бы есть в .gitignore. Не пойму почему не скрываются. Или уже ушедшие файлы нужно удалить? Таже история и с .env файлом.

2017-12-27 18:06 UTC, gis23 commented on docker-compose.yml
> +      - '9090:${prometheus_port}'
Поправил.

2017-12-27 18:07 UTC, gis23 commented on docker-compose.yml
> +      - '8080:${cadvisor_port}'
Тоже поправил.

2017-12-27 18:07 UTC, gis23 commented on docker-compose.yml
> +      - 3000:${grafana_port}
Исправил.

2017-12-27 18:07 UTC, gis23 commented on docker-compose.yml
> +      - 9093:${alertmanager_port}
Спасибо. Исправил.

2017-12-28 10:30 UTC, chromko commented on comment/build_info.txt
> +713dce6
Да, их нужно сначала удалить из индекса

2017-12-28 10:32 UTC, chromko reviewed
Изменения принимаю. Перед мерджем только удалить заигноренные файлы.

2017-12-28 10:32 UTC, chromko approved these changes

2017-12-29 16:47 UTC, merged